Repository martchellop/Entretenibit, pull requests merged in 2018-05, with the labels that each got.

#43 Improve Marcello's pull request
  Documents/Deliverables/7-May21-interview_planning.md
  Documents/Meetings/7-May21-interview_planning.md
Labels: Review requiered, documentation, priority: medium

#68 Server
  server/.gitignore
  server/README.md
  server/app.js
  server/bin/www
  server/package.json
  server/src/queries.js
  server/src/routes.js
  server/views/error.jade
  server/views/index.jade
  server/views/layout.jade
  server/yarn.lock
Labels: Review requiered, enhancement, priority: high

#70 Scrape a single event.
  Documents/Definition/3-May28-eventRelationalModel.pdf
  Documents/Definition/3-May28-eventRelationalModel.xml
  robot/.gitignore
  robot/Dockerfile
  robot/Event.py
  robot/Location.py
  robot/Occurence.py
  robot/Robot.py
  robot/app.py
  robot/modelagem_scraper.jpg
  robot/requirements.txt
  robot/scrapers/ICMCEventsScraper.py
  robot/scrapers/MTScraper.py
  robot/scrapers/ScraperBase.py
  robot/scrapers/__init__.py
Labels: Review requiered, enhancement, priority: higest

#72 Header component
  frontend/src/App.js
  frontend/src/Header/Header.js
Labels: Review requiered, enhancement
