Repository martchellop/Entretenibit, pull requests merged in 2018-06, with the labels that each got.

#79 Translate Roles.md
  Documents/Roles.md
Labels: documentation

#80 'Main' and 'Select' website pages integration
  frontend/src/App.js
  frontend/src/Header/Header.js
  frontend/src/SearchBar/SearchBar.js
  frontend/src/SearchButton/SearchButton.js
  frontend/src/SelectPage/SelectPage.js
Labels: Review requiered, enhancement

#81 Server
  server/.gitignore
  server/README.md
  server/package.json
  server/src/queries.js
  server/src/routes.js
  server/yarn.lock
Labels: Review requiered, enhancement, priority: medium

#76 Instanciating Database
  Documents/Construction/Database ER Diagram.pdf
  robot/createDB.sql
Labels: Review requiered, documentation, enhancement, priority: high

#82 Added cards for showing events
  frontend/public/card_icon_academic.png
  frontend/public/card_icon_box.png
  frontend/public/card_icon_theater.png
  frontend/public/card_icon_trumpet.png
  frontend/src/CardGrid/CardGrid.js
  frontend/src/CardGrid/SingleCard.js
  frontend/src/SelectPage/SelectPage.js
  frontend/src/index.js
  frontend/src/registerServiceWorker.js
Labels: enhancement

#83 Advanced Search Settings
  frontend/src/App.js
  frontend/src/Header/Header.js
  frontend/src/SelectPage/ConfigSettings/AdvancedSearch.js
  frontend/src/SelectPage/ConfigSettings/ConfigurationSettingsPanel.js
  frontend/src/SelectPage/ConfigSettings/DatePickers.js
  frontend/src/SelectPage/ConfigSettings/EventTypesCheckboxes.js
  frontend/src/SelectPage/ConfigSettings/PricePickers.js
  frontend/src/SelectPage/SelectPage.js
Labels: Review requiered, enhancement, priority: high

#84 User click card added
  frontend/package.json
  frontend/src/CardGrid/CardGrid.js
  frontend/src/CardGrid/ClickedCard.js
  frontend/src/CardGrid/SingleCard.js
  frontend/yarn.lock
  server/package.json
  server/yarn.lock
Labels: Review requiered, enhancement, priority: high

#88 Add June 4th meeting conclusions
  Documents/Meetings/9-June4-meeting-inClass.md
Labels: documentation

#102 Implement tests for Robot
  .travis.yml
  Documents/Construction/2-May31-robotDetails.md
  robot/2-May31-robotDetails.md
  robot/Robot.py
  robot/Robot_test.py
  robot/requirements.txt
  robot/scrapers/ICMCEventsScraper.py
  robot/scrapers/scrapers_test.py
  robot/scrapers/test_pages/ICMCEventsScraper-test.html
  test.bash
Labels: documentation, enhancement

#100 Server in container
  server/Dockerfile
  server/README.md
Labels: Review requiered, enhancement, priority: high

#103 Add yesterday's meetings conclusions
  Documents/Meetings/10-June5-meeting-secretGarden.md
Labels: daily

#106 Frontend dockerfile
  frontend/Dockerfile
  frontend/README.md
  server/Dockerfile
  server/README.md
  server/src/queries.js
  server/src/routes.js
Labels: Review requiered, enhancement, priority: high

#110 Add today's meeting conclusions
  Documents/Meetings/9-June8-meeting-inClass.md
Labels: daily

#109 Show cards
  frontend/package.json
  frontend/public/index.html
  frontend/src/CardGrid/CardGrid.js
  frontend/src/CardGrid/ClickedCard.js
  frontend/src/SelectPage/SelectPage.js
  frontend/src/api/server.js
  frontend/yarn.lock
  server/app.js
  server/bin/www
  server/package.json
  server/src/queries.js
  server/src/routes.js
  server/yarn.lock
Labels: Review requiered, priority: high

#114 About Us page
  frontend/src/AboutUsPage/AboutUsPage.js
  frontend/src/AboutUsPage/Images/Generic_Avatar.png
  frontend/src/App.js
Labels: Review requiered, priority: medium

#112 Create docker compose
  README.md
  docker-compose.yml
Labels: Review requiered, enhancement, priority: high

#115 Add today's meeting conclusions
  Documents/Meetings/11-June8-meeting-inClass.md
  Documents/Meetings/12-June11-meeting-inClass.md
Labels: daily

#127 Changed to soft tabs
  frontend/src/AboutUsPage/AboutUsPage.js
  frontend/src/App.js
  frontend/src/CardGrid/SingleCard.js
  frontend/src/Header/Header.js
  frontend/src/SearchBar/SearchBar.js
  frontend/src/SearchButton/SearchButton.js
  frontend/src/SelectPage/ConfigSettings/AdvancedSearch.js
  frontend/src/SelectPage/ConfigSettings/ConfigurationSettingsPanel.js
  frontend/src/SelectPage/ConfigSettings/DatePickers.js
  frontend/src/SelectPage/ConfigSettings/EventTypesCheckboxes.js
  frontend/src/SelectPage/ConfigSettings/PricePickers.js
  server/src/queries.js
Labels: Review requiered, type:refactor

#129 Add tests for Frontend
  .travis.yml
  test.bash
Labels: type:test

#131 Update schema
  robot/createDB.sql
Labels: Review requiered

#130 Add tests for Robot
  robot/scrapers/scrapers_test.py
  robot/scrapers/test_pages/UFSCarEventsScraper-test.html
Labels: type:test

#136 Remove the home page
  frontend/src/App.js
  frontend/src/Header/Header.js
  frontend/src/SelectPage/SearchBar/SearchBar.js
  frontend/src/SelectPage/SearchButton/SearchButton.js
  frontend/src/SelectPage/SelectPage.js
Labels: Review requiered, priority: highest, type:refactor

#138 Add test planning
  Documents/Construction/3-June15-files/imagem1.jpg
  Documents/Construction/3-June15-files/imagem2.jpg
  Documents/Construction/3-June15-files/imagem3.jpg
  Documents/Construction/3-June15-testPlanning.md
  Documents/Meetings/13-June15-meeting-inClass.md
Labels: documentation

#139 State uplift
  frontend/src/.gitignore
  frontend/src/AboutUsPage/AboutUsPage.js
  frontend/src/CardGrid/CardGrid.js
  frontend/src/CardGrid/SingleCard.js
  frontend/src/SelectPage/ConfigSettings/AdvancedSearch.js
  frontend/src/SelectPage/ConfigSettings/ConfigurationSettingsPanel.js
  frontend/src/SelectPage/ConfigSettings/DatePickers.js
  frontend/src/SelectPage/ConfigSettings/EventTypesCheckboxes.js
  frontend/src/SelectPage/ConfigSettings/PricePickers.js
  frontend/src/SelectPage/SelectPage.js
  frontend/src/api/server.js
Labels: enhancement, type:refactor

#141 Fix command on tutorial
  Documents/Tutorials/1-May4-postgres-server-usage.md
Labels: hotfix

#140 Create a sign up page
  frontend/src/App.js
  frontend/src/Header/Header.js
  frontend/src/SelectPage/ConfigSettings/ConfigurationSettingsPanel.js
  frontend/src/SelectPage/ConfigSettings/DatePickers.js
  frontend/src/SelectPage/ConfigSettings/PricePickers.js
  frontend/src/SelectPage/SearchBar/SearchBar.js
  frontend/src/SelectPage/SelectPage.js
  frontend/src/SignUpPage/LabelButtons/LabelButtons.js
  frontend/src/SignUpPage/SignUpPage.js
Labels: Review requiered, enhancement, priority: highest, type:refactor

#142 Advanced search (Beta version)
  frontend/src/CardGrid/CardGrid.js
  frontend/src/SelectPage/SelectPage.js
  frontend/src/api/server.js
  server/.gitignore
  server/src/queries.js
Labels: Review requiered, enhancement, priority: highest

#151 Update burnout chart for this sprint
  README.md
Labels: documentation

#152 Add today's meeting conclusions
  Documents/Meetings/14-June18-meeting-inClass.md
Labels: daily, documentation

#153 User data is now stored in the database
  createDB.sql
  frontend/src/App.js
  frontend/src/SignUpPage/SignUpPage.js
  frontend/src/api/server.js
  server/src/queries.js
  server/src/routes.js
Labels: Review requiered, enhancement

#156 Improved security of query building
  server/src/queries.js
Labels: Review requiered, priority: highest, type:refactor, type:security

#155 Add sweet alerts
  frontend/package.json
  frontend/src/App.js
Labels: enhancement

#169 Send 'unsubscribe' link to users
  robot/send_emails.py
  server/src/queries.js
  server/src/routes.js
Labels: enhancement, point: 21, priority: highest, type:security
